config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :cards do
    collection do
      get 'top'
    end
  end

  # Public pages
  root 'public#index'
  get 'random', to: 'public#random'
  get 'contact', to: 'contacts#new', as: 'contact'
  resources :contacts, only: %i[new create]
end

app/models/scryfall_service.rb
# frozen_string_literal: true

class ScryfallService < ApplicationRecord
  include HTTParty

  base_uri 'https://api.scryfall.com'

  def self.search(query)
    get("/cards/search?q=lang:fr+#{CGI.escape(query)}")
  end

  def self.card_price(name)
    get("/cards/named?exact=#{CGI.escape(name)}")
  end

  def self.random
    get('/cards/random?q=lang:fr')
  end
end

app/views/partials/_add_to_collection.html.erb
<% if user_signed_in? %>
  <%= form_for @card do |f| %>
    <% if card["layout"] == "transform" || card["layout"] == "modal_dfc" %>
      <%= f.hidden_field :name, value: card["card_faces"][0]["name"] %>
      <%= f.hidden_field :printed_name, value: card["card_faces"][0]["printed_name"] %>
      <%= f.hidden_field :image_uris, value: card["card_faces"][0]["image_uris"]["normal"] %>
    <% elsif card["layout"] == "adventure" %>
      <%= f.hidden_field :name, value: card["card_faces"][0]["name"] %>
      <%= f.hidden_field :printed_name, value: card["card_faces"][0]["printed_name"] %>
      <%= f.hidden_field :image_uris, value: card["image_uris"]["normal"] %>
    <% else %>
      <%= f.hidden_field :name, value: card["name"] %>
      <%= f.hidden_field :printed_name, value: card["printed_name"] %>
      <%= f.hidden_field :image_uris, value: card["image_uris"]["normal"] %>
    <% end %>
    <%= f.hidden_field :multiverse_ids, value: card["multiverse_ids"][0] %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :color_identity, value: card["color_identity"][0..-1] %>
    <%= f.hidden_field :quantity, value: 0 %>
    <%= f.hidden_field :price, value: card["prices"]["usd"] %>

    <%= f.submit "Ajouter", class: "btn btn-outline-primary d-grid gap-2 col-12 mx-auto" %>
  <% end %>
<% end %>

app/views/partials/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer class="bg-light py-3 mt-5">
  <div class="container">
    <div class="row">
      <div class="col text-center text-muted">
        <p class="mb-0">
          © Copyright <span>repairemagic.fr</span> | <%= link_to "Me contacter", contact_path %>.
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_has_more.html.erb
<div class="pagination d-flex justify-content-center">
  <% if @cards["has_more"] == true %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Attention!</strong>
      Votre recherche compte <%= @cards["total_cards"] %> cartes. Le site ne permet pas d'afficher plus de 175 cartes.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/partials/_hero.html.erb
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container text-center position-relative">
    <h1 class="d-block pb-3">Bienvenue sur le site de la <span class="d-block pb-3 background-gradient">Magie des cartes</span></h1>
    <a href="#about" class="btn-get-started scrollto">C'est parti !</a>
  </div>
</section><!-- End Hero -->

app/views/partials/_logo.html.erb
<a class="navbar-brand me-5" href="/" style="margin-right: -.1rem;">
  <svg width="180px" height="42px" viewBox="0 0 109 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
      <g id="app" fill="#FEFFFE">
        <path d="M18,0 C3.48268,0 0,3.4827 0,18 C0,32.51731 3.48268,36 18,36 C32.5173,36 36,32.51731 36,18 C36,
                3.4827 32.5173,0 18,0 Z M12.9043,25.95526 L7.25865,13.1243 C7.00203,12.501 6.78207,11.6946 6.78207,
                10.998 C6.78207,7.8086 9.01833,5.5723 12.2077,5.5723 C13.2529,5.5723 14.1208,5.8469 15.0033,
                6.1261 L15.004,6.1264 C15.9165,6.4152 16.8446,6.7088 18,6.7088 C19.1689,6.7088 20.0748,6.4178 20.9697,
                6.1302 L20.97,6.1301 C21.8432,5.8495 22.706,5.5723 23.7922,5.5723 C26.9816,5.5723 29.2179,
                7.8086 29.2179,10.998 C29.2179,11.6946 28.9979,12.501 28.7414,13.1243 L23.0958,25.95526 C22.1425,
                28.11819 20.3096,29.2913 18,29.2913 C15.6904,29.2913 13.8574,28.11819 12.9043,25.95526 Z M12.4277,
                11.1447 L18,23.7557 L23.499,11.1447 C21.9226,11.9146 19.943,12.2812 18,12.2812 C15.9837,12.2812 14.0774,
                11.9146 12.4277,11.1447 Z" id="Shape">
        </path>
        <text id="MyApp" font-size="15" font-weight="800" letter-spacing="0.50625">
          <tspan x="40" y="22">MagicBook</tspan>
        </text>
      </g>
    </g>
  </svg>
</a>

app/views/partials/_modals.html.erb
<% if @cards["data"] == nil %>
  <div class="container">
    <%= render "partials/not_found" %>
  </div>
<% else %>
  <%= render "partials/has_more" %>
  <% @cards["data"].each_with_index do |card, index| %>
    <div class="card" style="width: 18rem;">
      <% if card["layout"] == "transform" || card["layout"] == "modal_dfc" %>
        <!-- Modal for double faced cards with transform or modal_dfc layout -->
      <div class="modal fade" id="transformModalToggle" aria-hidden="true" aria-labelledby="transformModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="transformModalToggleLabel"><%= card["card_faces"][0]["printed_name"] %></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <img src="<%= card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top">
            </div>
            <div class="modal-footer">
              <button class="btn btn-primary" data-bs-target="#transformModalToggle2" data-bs-toggle="modal">Recto</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="transformModalToggle2" aria-hidden="true" aria-labelledby="transformModalToggleLabel2" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="transformModalToggleLabel2"><%= card["card_faces"][1]["printed_name"] %></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <img src="<%= card["card_faces"][1]["image_uris"]["normal"] %>" class="card-img-top">
            </div>
            <div class="modal-footer">
              <button class="btn btn-primary" data-bs-target="#transformModalToggle" data-bs-toggle="modal">Verso</button>
            </div>
          </div>
        </div>
      </div>
      <a href="#" data-bs-toggle="modal" data-bs-target="#transformModalToggle">
            <img src="https://img.icons8.com/ios-filled/50/000000/rotate-left.png" style="position: absolute; top: 0; right: 0;"/>
            <img src="<%= card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["card_faces"][0]["name"] %>">
          </a>
      <% else %>
        <!-- Modal for normal cards -->
        <div class="modal fade" id="normalModalToggle<%= index %>" aria-hidden="true" aria-labelledby="normalModalToggleLabel<%= index %>" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="normalModalToggleLabel<%= index %>"><%= card["printed_name"] %></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <img src="<%= card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["name"] %>">
              </div>
              <div class="modal-footer">
                <!-- Button add to deck in modal -->
                <%= link_to "Ajouter", search_cards_path(card_id: card["id"]), method: :post, class: "btn btn-primary" %>
                <button class="btn btn-secondary" data-bs-target="#normalModalToggle<%= index %>" data-bs-toggle="modal">Fermer</button>
              </div>
            </div>
          </div>
        </div>
        <a href="#" data-bs-toggle="modal" data-bs-target="#normalModalToggle<%= index %>">
          <img src="<%= card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["name"] %>">
        </a>
      <% end %>
    </div>
  <% end %>
  <%= render "partials/has_more" %>
<% end %>

app/views/partials/_modals_cards.html.erb
<% if @cards["data"] != nil %>
  <%= render "partials/has_more" %>
  <% @cards["data"].each_with_index do |card, index| %>
    <div class="card" style="width: 18rem;">
      <% if card["layout"] == "transform" || card["layout"] == "modal_dfc" %>
        <!-- Modal for double faced cards with transform or modal_dfc layout -->
        <div class="modal fade" id="transformModalToggle" aria-hidden="true" aria-labelledby="transformModalToggleLabel" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="transformModalToggleLabel"><%= card["card_faces"][0]["printed_name"] %></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <img src="<%= card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top">
              </div>
              <div class="modal-footer">
                <%= render "partials/add_to_collection", card: card %>
                <button class="btn btn-secondary" data-bs-target="#transformModalToggle2" data-bs-toggle="modal">Recto</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="transformModalToggle2" aria-hidden="true" aria-labelledby="transformModalToggleLabel2" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="transformModalToggleLabel2"><%= card["card_faces"][1]["printed_name"] %></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <img src="<%= card["card_faces"][1]["image_uris"]["normal"] %>" class="card-img-top">
              </div>
              <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-target="#transformModalToggle" data-bs-toggle="modal">Verso</button>
              </div>
            </div>
          </div>
        </div>
        <a href="#" data-bs-toggle="modal" data-bs-target="#transformModalToggle">
          <img src="https://img.icons8.com/ios-filled/50/000000/rotate-left.png" style="position: absolute; top: 0; right: 0;"/>
          <img src="<%= card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["card_faces"][0]["name"] %>">
        </a>
        <%= render "partials/add_to_collection", card: card %>
      <% else %>
        <!-- Modal for normal cards -->
        <div class="modal fade" id="normalModalToggle<%= index %>" aria-hidden="true" aria-labelledby="normalModalToggleLabel<%= index %>" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="normalModalToggleLabel<%= index %>"><%= card["printed_name"] %></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <img src="<%= card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["name"] %>">
              </div>
              <div class="modal-footer">
                <%= render "partials/add_to_collection", card: card %>
                <button class="btn btn-secondary" data-bs-target="#normalModalToggle<%= index %>" data-bs-toggle="modal">Fermer</button>
              </div>
            </div>
          </div>
        </div>
        <a href="#" data-bs-toggle="modal" data-bs-target="#normalModalToggle<%= index %>">
          <img src="<%= card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["name"] %>">
        </a>
        <%= render "partials/add_to_collection", card: card %>
      <% end %>
    </div>
  <% end %>
  <%= render "partials/has_more" %>
<% end %>

app/views/partials/_modals_random.html.erb
<!-- modal -->
<div class="row justify-content-center">
  <div class="col-9 col-lg-4 col-xxl-3 mb-12 mt-5">
    <% if @card["layout"] == "transform" || @card["layout"] == "modal_dfc" %>
      <!-- Modal for double faced cards with transform or modal_dfc layout -->
      <div class="modal fade" id="transformModalToggle" aria-hidden="true" aria-labelledby="transformModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="transformModalToggleLabel"><%= @card["card_faces"][0]["printed_name"] %></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <img src="<%= @card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top">
            </div>
            <div class="modal-footer">
              <button class="btn btn-primary" data-bs-target="#transformModalToggle2" data-bs-toggle="modal">Recto</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="transformModalToggle2" aria-hidden="true" aria-labelledby="transformModalToggleLabel2" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="transformModalToggleLabel2"><%= @card["card_faces"][1]["printed_name"] %></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <img src="<%= @card["card_faces"][1]["image_uris"]["normal"] %>" class="card-img-top">
            </div>
            <div class="modal-footer">
              <button class="btn btn-primary" data-bs-target="#transformModalToggle" data-bs-toggle="modal">Verso</button>
            </div>
          </div>
        </div>
      </div>
      <a href="#" data-bs-toggle="modal" data-bs-target="#transformModalToggle">
        <img src="https://img.icons8.com/ios-filled/50/000000/rotate-left.png" style="position: absolute; top: 0; right: 0;"/>
        <img src="<%= @card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top" alt="<%= @card["card_faces"][0]["printed_name"] %>">
      </a>
    <% else %>
      <div class="modal fade" id="normalModalToggle" aria-hidden="true" aria-labelledby="normalModalToggleLabel" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="normalModalToggleLabel"><%= @card["printed_name"] %></h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <img src="<%= @card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= @card["name"] %>">
          </div>
          <div class="modal-footer">
            <%#= link_to "Ajouter", search_cards_path(card_id: card["id"]), method: :post, class: "btn btn-primary" %>
            <button class="btn btn-secondary" data-bs-target="#normalModalToggle" data-bs-toggle="modal">Fermer</button>
          </div>
        </div>
      </div>
    </div>
    <a href="#" data-bs-toggle="modal" data-bs-target="#normalModalToggle">
      <img src="<%= @card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= @card["name"] %>">
    </a>
  <% end %>
</div>

app/views/partials/_navbar.html.erb
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container">
    <div class="header-container d-flex align-items-center justify-content-between">
      <div class="logo">
        <h1 class="text-light"><a href="<%= root_path %>"><span>Repaire Magic</span></a></h1>
      </div>
      <div class="beta d-flex align-items-center" style="padding-left: 15px;">
        <!-- <span style="font-size: 14px; font-weight: bold; color: black;">Version bêta 0.29</span> -->
      </div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Repaire Magic</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= root_path %>">Accueil</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= cards_path %>">Collection</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Outils
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                    <li><a class="dropdown-item" href="<%= random_path %>">Carte aléatoire</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="<%= top_cards_path %>">Top 10</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_card_path %>">Recherche tes cartes</a>
                </li>
              </ul>
              <%= render 'user/session_manager' %>
            </div>
          </div>
        </div>
      </nav>
    </div><!-- End Header Container -->
  </div>
</header><!-- End Header -->

app/views/partials/_normal_card_modal.html.erb
<div class="modal fade" id="normalModalToggle<%= index %>" aria-hidden="true" aria-labelledby="normalModalToggleLabel<%= index %>" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="normalModalToggleLabel<%= index %>"><%= card["printed_name"] %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="<%= card["image_uris"]["normal"] %>" class="card-img-top" alt="<%= card["name"] %>">
      </div>
      <div class="modal-footer">
        <%= render "partials/add_to_collection", card: card %>
        <button class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_not_cards.html.erb
<% if @cards.sum(:quantity) == 0 %>
  <div class="container text-center mt-5">
    <img src="https://images.ctfassets.net/s5n2t79q9icq/6CD1NIljkydWyaviTmJ616/26610f46dfa9f43123d355f503528aaa/d3jaJtb4gJk-1920x700.jpg?q=80&w=1920&h=700&fit=crop&f=center&fm=avif" alt="carte magic the gathering" class="img-fluid">
    <h2>Oh non !</h2>
    <p>
      Tu n'as aucune carte dans ta collection.
    </p>
    <p>
      <strong>Ajoute des cartes à ta collection en cliquant sur le bouton ci-dessous.</strong>
    </p>
    <p>
      <a href="/cards/new" class="btn btn-secondary">Ajouter des cartes</a>
    </p>
  </div>
<% end %>

app/views/partials/_not_found.html.erb
<div class="error_window" role="alert">
  <img src="https://images.ctfassets.net/s5n2t79q9icq/6rdW8PbWVohxvAum5Q20sN/e41ed9f2bda29bc8e39cfecec1e5761a/icon_768x432_capenna_express.jpg?fm=webp" alt="carte magic the gathering" class="img-fluid">
  <h2> Le Capenna Express</h2>
  <p>
    Celui-ci est arrivé à destination, il est temps de trouver un moyen de le faire partir.
  </p>
  <p>
    <strong>Veuillez réessayer avec un autre nom.</strong>
  </p>
  <p>
    <a href="<%= root_path %>" class="btn btn-secondary">Retour à l'accueil</a>
  </p>
</div>

app/views/partials/_transform_card_modal.html.erb
<!-- _transform_card_modal.html.erb -->
<div class="modal fade" id="transformModalToggle<%= index %>" aria-hidden="true" aria-labelledby="transformModalToggleLabel<%= index %>" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="transformModalToggleLabel<%= index %>"><%= card["card_faces"][0]["printed_name"] %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="<%= card["card_faces"][0]["image_uris"]["normal"] %>" class="card-img-top">
      </div>
      <div class="modal-footer">
        <%= render "partials/add_to_collection", card: card %>
        <button class="btn btn-secondary" data-bs-target="#transformModalToggle2<%= index %>" data-bs-toggle="modal">Recto</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="transformModalToggle2<%= index %>" aria-hidden="true" aria-labelledby="transformModalToggleLabel2<%= index %>" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="transformModalToggleLabel2<%= index %>"><%= card["card_faces"][1]["printed_name"] %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="<%= card["card_faces"][1]["image_uris"]["normal"] %>" class="card-img-top">
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-bs-target="#transformModalToggle<%= index %>" data-bs-toggle="modal">Verso</button>
      </div>
    </div>
  </div>
</div>